/*
    SQL В ПРИМЕРАХ И ЗАДАЧАХ.
    ISBN 985-475-004-3

    Exercises from page 27 and 28.
*/

-- 1
SELECT * FROM SUBJECT_Table;

-- 2
SELECT * FROM EXAM_MARKS WHERE SUBJ_ID = 12;

-- 3
SELECT KURS, SURNAME, FIRSTNAME, STIPEND FROM STUDENT;

-- 4
SELECT SUBJ_NAME, HOUR FROM SUBJECT_TABLE WHERE SEMESTER = 4;

-- 5
SELECT DISTINCT MARK FROM EXAM_MARKS;

-- 6
SELECT SURNAME FROM STUDENT WHERE KURS >= 3;

-- 7
SELECT SURNAME, FIRSTNAME, KURS FROM STUDENT WHERE STIPEND > 140;

-- 8
SELECT SUBJ_NAME FROM SUBJECT_TABLE WHERE HOUR > 30;

-- 9
SELECT UNIV_NAME FROM UNIVERSITY WHERE RATING > 300;

-- 10
SELECT SURNAME, FIRSTNAME, KURS FROM STUDENT WHERE STIPEND >= 100 AND CITY LIKE 'Воронеж';

-- 11
SELECT * FROM STUDENT WHERE (stipend < 100 OR NOT ( birthday >= '10-03-1980' and student_id > 103));

-- 12
SELECT * FROM STUDENT where NOT ((birthday = '10-03-1980' or stipend > 100) and student_id >= 103);
