/*
    SQL В ПРИМЕРАХ И ЗАДАЧАХ.
    ISBN 985-475-004-3
    Exercises from page 74
*/

-- 1
SELECT SURNAME, SUBJ_ID FROM STUDENT A JOIN EXAM_MARKS B ON A.STUDENT_ID = B.STUDENT_ID;

-- 2
SELECT  SURNAME, SUBJ_ID FROM STUDENT A LEFT OUTER JOIN EXAM_MARKS B ON A.STUDENT_ID = B.STUDENT_ID;

-- 3
SELECT  surname, subj_name FROM STUDENT A, EXAM_MARKS B, SUBJECT_TABLE C WHERE A.STUDENT_ID = B.STUDENT_ID AND B.SUBJ_ID=C.SUBJ_ID;

-- 4



-- 5
SELECT SURNAME, subj_name, MARK FROM STUDENT A, EXAM_MARKS B, SUBJECT_TABLE C WHERE A.STUDENT_ID = B.STUDENT_ID  AND B.SUBJ_ID = C.SUBJ_ID AND MARK>=4;

-- 6
SELECT univ_name, MAX(stipend) FROM STUDENT A JOIN UNIVERSITY B ON A.univ_id = B.univ_id AND RATING>300 GROUP BY univ_name;

-- 7
SELECT SURNAME, RATING FROM STUDENT A LEFT OUTER JOIN UNIVERSITY B ON A.univ_id = B.univ_id ORDER BY SURNAME;