/*
    SQL В ПРИМЕРАХ И ЗАДАЧАХ.
    ISBN 985-475-004-3
    Exercises from page 63
*/

-- 1
SELECT * FROM UNIVERSITY WHERE rating >= ANY(SELECT rating FROM UNIVERSITY WHERE CITY='Воронеж');

-- 2
SELECT * FROM STUDENT WHERE NOT CITY = ANY(SELECT CITY FROM UNIVERSITY);

-- 3
SELECT SUBJ_ID FROM EXAM_MARKS WHERE MARK > ALL(SELECT MARK FROM EXAM_MARKS WHERE SUBJ_ID=10);

-- 4
SELECT SUBJ_ID FROM EXAM_MARKS WHERE MARK>ALL (SELECT MAX(MARK) FROM EXAM_MARKS WHERE SUBJ_ID=10);