/*
    SQL В ПРИМЕРАХ И ЗАДАЧАХ.
    ISBN 985-475-004-3

    Page 22. UNIVERSITY Table.
*/

CREATE TABLE SUBJ_LECT (
    LECTURER_ID INTEGER NOT NULL Primary key,
    SUBJ_ID     INTEGER
);

INSERT INTO SUBJ_LECT (LECTURER_ID, SUBJ_ID)
    VALUES (24, 24);

INSERT INTO SUBJ_LECT (LECTURER_ID, SUBJ_ID)
    VALUES (46, 46);

INSERT INTO SUBJ_LECT (LECTURER_ID, SUBJ_ID)
    VALUES (74, 74);

INSERT INTO SUBJ_LECT (LECTURER_ID, SUBJ_ID)
    VALUES (108, 108);

INSERT INTO SUBJ_LECT (LECTURER_ID, SUBJ_ID)
    VALUES (276, 276);

INSERT INTO SUBJ_LECT (LECTURER_ID, SUBJ_ID)
    VALUES (328, 328);
