
-- insert some values
INSERT INTO personalities
    (personality_id,
    surname,
    firstname,
    patronymic,
    academic_degree,
    academic_rank,
    scientific_direction,
    place_of_work,
    department,
    position,
    country,
    city,
    postcode,
    home_address,
    work_phone,
    home_phone,
    e_mail)
VALUES
    (
        1,
        'Toretto',
        'Elovit',
        'Sergio',
        'Doctor of Mathematics',
        'Docent',
        'Mathematics',
        'Moscow State University',
        'Discrete Mathematics',
        'Lecturer',
        'Russia',
        'Moscow',
        '191028',
        'g. MOSKVA, ul. Lesnaya d. 5, kv. 176',
        '+79535554156',
        '+79025556911',
        'torettoelovit@mail.ru'
    );

INSERT INTO personalities
    (personality_id,
    surname,
    firstname,
    patronymic,
    academic_degree,
    academic_rank,
    scientific_direction,
    place_of_work,
    department,
    position,
    country,
    city,
    postcode,
    home_address,
    work_phone,
    home_phone,
    e_mail)
VALUES
    (
        2,
        'Glazkov',
        'Andrei',
        'Abramovich',
        'Doctor of Mathematics',
        'Professor',
        'Mathematics',
        'Moscow State University',
        'Probability Theory and Statistics',
        'Lecturer',
        'Russia',
        'Moscow',
        '191122',
        'g. MOSKVA, ul. Lesnaya d. 5, kv. 123',
        '+79045552188',
        '+79525551898',
        'glazkovandrei@yandex.ru'
    );
    
INSERT INTO personalities
    (personality_id,
    surname,
    firstname,
    patronymic,
    academic_degree,
    academic_rank,
    scientific_direction,
    place_of_work,
    department,
    position,
    country,
    city,
    postcode,
    home_address,
    work_phone,
    home_phone,
    e_mail)
VALUES
    (
        3,
        'Kostin',
        'Ivan',
        'Ivanovich',
        'Master of Science',
        'Assistant Lecturer',
        'Mathematics',
        'Moscow State University',
        'Geometry and Topology',
        'Lecturer',
        'Russia',
        'Moscow',
        '191201',
        'g. MOSKVA, ul. Qaqarina d. 2, kv. 32',
        '+79045642152',
        '+79521253890',
        'ivankostin@gmail.com'
    );

INSERT INTO personalities
    (personality_id,
    surname,
    firstname,
    patronymic,
    academic_degree,
    academic_rank,
    scientific_direction,
    place_of_work,
    department,
    position,
    country,
    city,
    postcode,
    home_address,
    work_phone,
    home_phone,
    e_mail)
VALUES
    (
        4,
        'Sidorov',
        'Taras',
        'Stepanovich',
        'Master of Science',
        'Assistant Lecturer',
        'Mathematics',
        'Moscow State University',
        'Programming',
        'Lecturer',
        'Russia',
        'Moscow',
        '191312',
        'g. MOSKVA, ul. Qaqarina d. 2, kv. 35',
        '+79043656152',
        '+79523283790',
        'tarasstepan@gmail.com'
    );

INSERT INTO personalities
    (personality_id,
    surname,
    firstname,
    patronymic,
    academic_degree,
    academic_rank,
    scientific_direction,
    place_of_work,
    department,
    position,
    country,
    city,
    postcode,
    home_address,
    work_phone,
    home_phone,
    e_mail)
VALUES
    (
        5,
        'Vasilyev',
        'Vlad',
        'Vityaovich',
        'Master of Science',
        'Assistant Lecturer',
        'Mathematics',
        'Moscow State University',
        'Statistics',
        'Lecturer',
        'Russia',
        'Moscow',
        '192300',
        'g. MOSKVA, ul. Uriya d. 4, kv. 5',
        '+79043626012',
        '+79523829799',
        'vladvasilyev@yandex.ru'
    );

INSERT INTO personalities
    (personality_id,
    surname,
    firstname,
    patronymic,
    academic_degree,
    academic_rank,
    scientific_direction,
    place_of_work,
    department,
    position,
    country,
    city,
    postcode,
    home_address,
    work_phone,
    home_phone,
    e_mail)
VALUES
    (
        6,
        'Preobrazhensky',
        'Roman',
        'Rolanovich',
        'Doctor of Science',
        'Docent',
        'Mathematics',
        'Moscow State University',
        'Mechanics',
        'Lecturer',
        'Russia',
        'Moscow',
        '197120',
        'g. MOSKVA, ul. Uriya d. 2, kv. 24',
        '+79043698032',
        '+79523122787',
        'rolanovichpreobr@yandex.ru'
    );